export const data = [
    {
      id: 1,
      title: "Kitob",
      children: [
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
        {id:'ka', name:""},
      ],
      icon: "https://assets.asaxiy.uz/category//5e0158017e038.png",
      link:'/product/books'
    },
    {
      id: 2,
      title: "Telefonlar va gadjetlar",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//5e0153249b10a.png",
      link:'/product/phone'
    },
    {
      id: 3,
      title: "Konditsionerlar",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category/air-conditioner.png",
      link:'/product/books'
    },
    {
      id: 4,
      title: "Kompyuterlar va orgtexnika",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//5e01560bef0bb.png",
      link:'/product/phone'
    },
    {
      id: 5,
      title: "Geymerlar uchun",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//5fd9fbdaec848.png",
      link:'/product/phone'
    },
    {
      id: 6,
      title: "Maishiy texnika",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//5e0154abcfc0e.png",
      link:'/product/televison'
    },
    {
      id: 7,
      title: "Televizorlar, video va audio",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//5e015729184f2.png",
      link:'/televizorlar'
    },
    {
      id: 8,
      title: "Idish-tovoqlar",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//kitchen2.png",
      link:'/product/sports'
    },
    {
      id: 9,
      title: "Mebel",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category/wardrobe.png",
      link:'/product/books'
    },
    {
      id: 10,
      title: "Sport va dam olish",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//62be096a99c6d.jpeg",
      link:'/product/sports'
    },
    {
      id: 11,
      title: "Uy va ofis uchun texnika va jihozlar",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//5e0157aa83115.jpg",
      link:'/product/televison'
    },
    {
      id: 12,
      title: "Avto",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//5e01568229ad0.png",
    },
    {
      id: 13,
      title: "O‘yinchoqlar, sovg‘alar va aksessuarlar",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//5fb29e5f8b8a8.png",
    },
    {
      id: 14,
      title: "Kiyim, poyabzal va aksessuarlar",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//609532076b3e6.png",
    },
    {
      id: 15,
      title: "Bolalar uchun tovarlar",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//611662dbc91da.png",
    },
    {
      id: 16,
      title: "Goʻzallik va salomatlik",
      children: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      icon: "https://assets.asaxiy.uz/category//62c55b4f2bbf2.png",
    },
  ];