
export const province = [
    {id:"v1", name:"Toshkent shahri",},
    {id:"v2", name:"Andijon viloyati",},
    {id:"v3", name:"Buxoro viloyati",},
    {id:"v4", name:"Jizzax viloyati",},
    {id:"v5", name:"Qashqadaryo viloyati",},
    {id:"v6", name:"Navoiy viloyati",},
    {id:"v7", name:"Namangan viloyati",},
    {id:"v8", name:"Samarqand viloyati",},
    {id:"v9", name:"Surxondaryo viloyati",},
    {id:"v10", name:"Sirdaryo viloyati",},
    {id:"v11", name:"Toshkent viloyati",},
    {id:"v12", name:"Farg'ona viloyati",},
    {id:"v13", name:"Toshkent viloyati",},
    {id:"v14", name:"Qoraqalpog'iston Respublikasi",},
]

// Navoiy vil
export const NavoiyVil = [
    {id:"ct1", name:"Karmana tumani",value:1},
    {id:"ct3", name:"Komeneks tumani",value:2},
    {id:"ct2", name:"Navbahor tumani",value:3},
    {id:"ct4", name:"Navoiy shahri",value:4},
    {id:"ct5", name:"Nurota tumani",value:5},
    {id:"ct6", name:"Qiziltepa tumani",value:6},
    {id:"ct7", name:"Tomdi tumani",value:7},
    {id:"ct8", name:"Uchquduq tumani",value:8},
    {id:"ct9", name:"Xatirchi timani shahri",value:9},
    {id:"ct10", name:"Zarafshon shahri",value:10},
]

export const karmanaTumani = [
    {id:"v1", name:"Bag'ot ",value:""},
    {id:"v1", name:"Chutqora",value:""},
    {id:"v1", name:"Chuyut",value:""},
    {id:"v1", name:"Damburkut shahri",value:""},
    {id:"v1", name:"Dormon",value:""},
    {id:"v1", name:"Gulobod",value:""},
    {id:"v1", name:"Gulshan",value:""},
    {id:"v1", name:"Gurda",value:""},
    {id:"v1", name:"Karmana shaharchasi",value:""},
    {id:"v1", name:"Malik rabot shaharchasi",value:""},
    {id:"v1", name:"O'rtaqo'rg'on",value:""},
    {id:"v1", name:"Paraganda",value:""},
    {id:"v1", name:"Qahramon",value:""},
    {id:"v1", name:"Qiyot ",value:""},
    {id:"v1", name:"Toshobod ",value:""},
    {id:"v1", name:"Uyrot ",value:""},
    {id:"v1", name:"Uzumzor ",value:""},
    {id:"v1", name:"Yangiariq ",value:""},
    {id:"v1", name:"Yangi qurulish ",value:""},
    {id:"v1", name:" Yoshlik shaharchasi",value:""},
]

export const conimexTumani = [
    {id:"v1", name:"Balakarak shaharchasi ",value:""},
    {id:"v1", name:"Chordara ",value:""},
    {id:"v1", name:"Davgustav ",value:""},
    {id:"v1", name:"Kenagas ",value:""},
    {id:"v1", name:"Ko'kcha ",value:""},
    {id:"v1", name:"Ko'neobod ",value:""},
    {id:"v1", name:"Konemex shaharchasi ",value:""},
    {id:"v1", name:"Noniqchi shaharchasi ",value:""},
    {id:"v1", name:"Qatag'on ",value:""},
    {id:"v1", name:"Qumriobod ",value:""},
    {id:"v1", name:"Shengeldi ",value:""},
    {id:"v1", name:"Shortepa shaharchasi ",value:""},
    {id:"v1", name:"Toqmang'it ",value:""},
    {id:"v1", name:"Yangiobod ",value:""},
    {id:"v1", name:"Zafarobod ",value:""},
]

export const navbahorTumani = [
    {id:"v1", name:"Arabxona ",value:""},
    {id:"v1", name:"Arminjon ",value:""},
    {id:"v1", name:"Beshrobod shaharchasi ",value:""},
    {id:"v1", name:"Davriqo'rg'on ",value:""},
    {id:"v1", name:"Duldul ",value:""},
    {id:"v1", name:"G'ujbog' ",value:""},
    {id:"v1", name:"Gulbog' ",value:""},
    {id:"v1", name:"Idjan shaharchasi ",value:""},
    {id:"v1", name:"Keskanterak shaharchasi ",value:""},
    {id:"v1", name:"Mang'it ",value:""},
    {id:"v1", name:"Mavlonbobo ",value:""},
    {id:"v1", name:"Mesit ",value:""},
    {id:"v1", name:"Mirzamo'min ",value:""},
    {id:"v1", name:"Mitti ",value:""},
    {id:"v1", name:"Olchin ",value:""},
    {id:"v1", name:"Oqoltin ",value:""},
    {id:"v1", name:"Paxtakor ",value:""},
    {id:"v1", name:"Po'lat-Oktabr ",value:""},
    {id:"v1", name:"Qalqonota shaharchasi ",value:""},
    {id:"v1", name:"Qiziloy ",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]

export const cityTashkent = [
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
    {id:"v1", name:"Toshkent shahri",value:""},
]