import React from "react";
import { Box } from "@mui/material";
import MyCheckBoxList from "../../Generic/CheckBoxList";

const data1 = [
  { id: 1, title: "1MORE" },
  { id: 2, title: "2E Gaming" },
  { id: 3, title: "A4Tech" },
  { id: 4, title: "AWEI" },
  { id: 5, title: "Al-Harameen" },
  { id: 6, title: "Anker" },
  { id: 7, title: "Apple" },
  { id: 8, title: "Audio-Technica" },
  { id: 9, title: "AverMedia" },
  { id: 10, title: "BQ-Mobile" },
  { id: 11, title: "Baseus" },
  { id: 12, title: "Belkin" },
  { id: 13, title: "Blackview" },
  { id: 14, title: "Borofone" },
  { id: 15, title: "Boya" },
  { id: 16, title: "Celebrat" },
  { id: 17, title: "DT NO.1" },
  { id: 18, title: "Devia" },
  { id: 19, title: "Digma" },
  { id: 20, title: "Edifier" },
  { id: 21, title: "Elgato" },
  { id: 22, title: "Garmin" },
  { id: 23, title: "Gigaset" },
  { id: 24, title: "Google" },
  { id: 25, title: "Grandstream" },
  { id: 26, title: "Green Lion" },
  { id: 27, title: "Haino Teko" },
  { id: 28, title: "Harman/Kardon" },
  { id: 29, title: "Havit" },
  { id: 30, title: "Haylou" },
  { id: 31, title: "Hoco" },
  { id: 32, title: "Honor" },
  { id: 33, title: "Huawei" },
  { id: 34, title: "HyperX" },
  { id: 35, title: "Hytera" },
  { id: 36, title: "IPEGA" },
  { id: 37, title: "Infinix" },
  { id: 38, title: "Inoi" },
  { id: 39, title: "JBL" },
  { id: 40, title: "JOYROOM" },
  { id: 41, title: "Jmary" },
  { id: 42, title: "K-doo" },
  { id: 43, title: "KingKong" },
  { id: 44, title: "Kingston" },
  { id: 45, title: "LDNIO" },
  { id: 46, title: "Nia" },
  { id: 47, title: "Nillkin" },
  { id: 48, title: "Nokia" },
  { id: 49, title: "Novey" },
  { id: 50, title: "OnePlus" },
  { id: 51, title: "Panasonic" },
  { id: 52, title: "Philips" },
  { id: 53, title: "Pioneer" },
  { id: 54, title: "PocketBook" },
  { id: 55, title: "Porodo" },
  { id: 56, title: "PowerGym" },
  { id: 57, title: "Powerology" },
  { id: 58, title: "QCY" },
  { id: 59, title: "RIVACASE" },
  { id: 60, title: "Rapoo" },
  { id: 61, title: "Razer" },
  { id: 62, title: "Realme" },
  { id: 63, title: "Redmi" },
  { id: 64, title: "Remax" },
  { id: 65, title: "SHINECON" },
  { id: 66, title: "Samos" },
  { id: 67, title: "Samsung" },
  { id: 68, title: "Saramonic" },
  { id: 69, title: "Sennheiser" },
  { id: 70, title: "Sharp" },
  { id: 71, title: "Sony" },
  { id: 72, title: "Sven" },
  { id: 73, title: "Tebaurry" },
  { id: 74, title: "Trust" },
  { id: 75, title: "Ttec" },
  { id: 76, title: "VTECH" },
  { id: 77, title: "Vivo" },
  { id: 78, title: "XO" },
  { id: 79, title: "Xiaomi" },
  { id: 80, title: "Yesido" },
  { id: 81, title: "Yison" },
  { id: 82, title: "ZTE" },
  { id: 83, title: "Zeblaze" },
  { id: 84, title: "Zeblaze" },
  { id: 85, title: "ipipoo" },
  { id: 86, title: "Другие" },
  { id: 87, title: "Радиотелефоны" },
  { id: 88, title: "Яндекс" },
];

const IshlabChiquvchi = () => {
  return (
    <Box>
      <MyCheckBoxList mydata={data1} nomi="Ishlab Chiqaruvchi" />
    </Box>
  );
};
export default IshlabChiquvchi;
