import React from "react";
import { Box } from "@mui/material";
import MyCheckBoxList from "../../Generic/CheckBoxList";

const data1 = [
  { id: 1, title: "Adabiyot" },
  { id: 2, title: "Adolat" },
  { id: 3, title: '"Adolat" milliy huquqiy axborot markazi' },
  { id: 4, title: "Al Huda" },
  { id: 5, title: "Alisher Navoiy nomidagi O'zbekiston Milliy kutubxonasi" },
  { id: 6, title: "Alpina Publisher" },
  { id: 7, title: "Anorbooks" },
  { id: 8, title: "Arrow Books" },
  { id: 9, title: "ART FLEX" },
  { id: 10, title: "Asaxiy Books" },
  { id: 11, title: "Avto-olam" },
  { id: 12, title: "Azmir nashr print" },
  { id: 13, title: "Baktria press" },
  { id: 14, title: "Bantam" },
  { id: 15, title: "Bantam Books" },
  { id: 16, title: "Barron's Educational Series" },
  { id: 17, title: "Bayoz" },
  { id: 18, title: "BEST-BOOK" },
  { id: 19, title: "Bilim Makon" },
  { id: 20, title: "Bilim va intellektual salohiyat" },
  { id: 21, title: "Bishkek" },
  { id: 22, title: "Book Media Nashr" },
  { id: 23, title: "Buntar" },
  { id: 24, title: "Butikbooks" },
  { id: 25, title: "Cambridge University Press" },
  { id: 26, title: "Cho`lpon" },
  { id: 27, title: "Collins Cobuild" },
  { id: 28, title: "Corgi" },
  { id: 29, title: "Credo Print Group" },
  { id: 30, title: "Currency" },
  { id: 31, title: "Davlatov S" },
  { id: 32, title: "Dizayn Press" },
  { id: 33, title: "Donish chirog`i" },
  { id: 34, title: "Dorlion Yayinlari" },
  { id: 35, title: "Evrika nashriyot-matbaa uyi" },
  { id: 36, title: "extremum- press" },
  { id: 37, title: "Factor Books" },
  { id: 38, title: "Factor Press" },
  { id: 39, title: "Factor Press" },
  { id: 40, title: "Faktor Press Info" },
  { id: 41, title: "Fan" },
  { id: 42, title: "Fan ziyosi" },
  { id: 43, title: "Faylasuflar" },
  { id: 44, title: "Freedom" },
  { id: 45, title: "Future-Books" },
  { id: 46, title: "G`afur G`ulom" },
  { id: 47, title: "Global Book" },
  { id: 48, title: "Grove Press" },
  { id: 49, title: "Hamroh Books" },
  { id: 50, title: "Hilol media" },
  { id: 51, title: "Hyperion" },
  { id: 52, title: "Iftixor Books" },
  { id: 53, title: "Ijod nashr" },
  { id: 54, title: "Ijod-Press" },
  { id: 55, title: "Imom Buxoriy xalqaro markazi" },
  { id: 56, title: "Info Capital Books" },
  { id: 57, title: "Info Capital Group" },
  { id: 58, title: "Iqro-Nashr" },
  { id: 59, title: "Irfonnashr" },
  { id: 60, title: "Kamalak" },
  { id: 61, title: "Kamalak Press" },
  { id: 62, title: "Kitobdornashr" },
  { id: 63, title: "Lesson Press" },
  { id: 64, title: "Little, Brown and Company" },
  { id: 65, title: "Ma'naviyat" },
  { id: 66, title: "Ma'rifat bitiklari" },
  { id: 67, title: "Matbaachi" },
  { id: 68, title: "Matrix" },
  { id: 69, title: "Max Pristil" },
  { id: 70, title: "Meriyus" },
  { id: 71, title: "Mindbook Company" },
  { id: 72, title: "Misbah" },
  { id: 73, title: "Mohirbek-Ziyo" },
  { id: 74, title: "Muharrir" },
  { id: 75, title: "Munir" },
  { id: 76, title: "Musiqa" },
  { id: 77, title: "Namangan" },
  { id: 78, title: "Nasaf" },
  { id: 79, title: "Nasim Kutub" },
  { id: 80, title: "Navro`z" },
  { id: 81, title: "Neva" },
  { id: 82, title: "Noorly Moon" },
  { id: 83, title: "Noshir" },
  { id: 84, title: "Novda edutainment" },
  { id: 85, title: "Nurafshon biznes" },
  { id: 86, title: "Nurafshon business" },
  { id: 87, title: "Nurafshon-kitob-ta'minot" },
  { id: 88, title: "Ofset print" },
];

const Nashryot = () => {
  return (
    <Box>
      <MyCheckBoxList mydata={data1} nomi="Nashryot" />
    </Box>
  );
};
export default Nashryot;
